### USER ENDPOINTS / Create user
POST http://localhost:3030/api/v1/users
Content-Type: application/json
{ "userName": "Anna" }
### / Fetch user list (active inly)
GET http://localhost:3030/api/v1/users
### / Fetch user with ID
GET http://localhost:3030/api/v1/users/5e2a0dd52a0f69097fbf14e9
### / Update user with ID
PUT http://localhost:3030/api/v1/users/5deac1b5c4d2cf0a7b9c0969
Content-Type: application/json
{ "userName": "Dimitry" }
### / Delete User with ID (change status)
DELETE http://localhost:3030/api/v1/users/5dea8cc3f81968069de0ca28
### OFFICE ENDPOINTS / Fetch list of offices
GET http://localhost:3030/api/v1/offices
###
POST http://localhost:3030/api/v1/offices
Content-Type: application/json
{ "userId": "5e2a0dd52a0f69097fbf14e9" }
### WORKER ENDPOINTS
GET http://localhost:3030/api/v1/workers
###
POST http://localhost:3030/api/v1/workers
Content-Type: application/json
{
  "userId": "5e2a0dd52a0f69097fbf14e9",
  "officeId": "5e2b0347d8130e0b915046aa"
}
###
PUT http://localhost:3030/api/v1/workers/5defc7df6c9e8305fc58eeaa
Content-Type: application/json
{
  "officeId": "5deb55204bea240fb41b0044",
  "aura": 66
}
